Files regenerated after modifying main build files to use Qt5 to build xcwcp

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -645,8 +645,8 @@ WITH_EXPERIMENTAL_RECEIVER_TRUE
 LIBCW_WITH_SIGNALS_ALTERNATIVE_FALSE
 LIBCW_WITH_SIGNALS_ALTERNATIVE_TRUE
 MOC
-QT4_LIBS
-QT4_CFLAGS
+QT5_LIBS
+QT5_CFLAGS
 PKG_CONFIG_LIBDIR
 PKG_CONFIG_PATH
 PKG_CONFIG
@@ -812,8 +812,8 @@ CXXCPP
 PKG_CONFIG
 PKG_CONFIG_PATH
 PKG_CONFIG_LIBDIR
-QT4_CFLAGS
-QT4_LIBS'
+QT5_CFLAGS
+QT5_LIBS'
 
 
 # Initialize some variables set by options.
@@ -1449,7 +1449,7 @@ Optional Features:
   --disable-pulseaudio    disable support for PulseAudio audio output
   --disable-cwcp          do not build cwcp (application with curses user
                           interface)
-  --disable-xcwcp         do not build xcwcp (application with Qt4 user
+  --disable-xcwcp         do not build xcwcp (application with Qt5 user
                           interface)
   --enable-signals-alternative
                           replace *some* cases of usage of POSIX signals in
@@ -1487,8 +1487,8 @@ Some influential environment variables:
               directories to add to pkg-config's search path
   PKG_CONFIG_LIBDIR
               path overriding pkg-config's built-in search path
-  QT4_CFLAGS  C compiler flags for QT4, overriding pkg-config
-  QT4_LIBS    linker flags for QT4, overriding pkg-config
+  QT5_CFLAGS  C compiler flags for QT5, overriding pkg-config
+  QT5_LIBS    linker flags for QT5, overriding pkg-config
 
 Use these variables to override the choices made by `configure' or to help
 it to find libraries and programs with nonstandard names/locations.
@@ -17071,19 +17071,19 @@ $as_echo "no" >&6; }
 fi
 
 pkg_failed=no
-{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for QT4" >&5
-$as_echo_n "checking for QT4... " >&6; }
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking for QT5" >&5
+$as_echo_n "checking for QT5... " >&6; }
 
-if test -n "$QT4_CFLAGS"; then
-    pkg_cv_QT4_CFLAGS="$QT4_CFLAGS"
+if test -n "$QT5_CFLAGS"; then
+    pkg_cv_QT5_CFLAGS="$QT5_CFLAGS"
  elif test -n "$PKG_CONFIG"; then
     if test -n "$PKG_CONFIG" && \
-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"QtCore QtGui >= 4.4.0\""; } >&5
-  ($PKG_CONFIG --exists --print-errors "QtCore QtGui >= 4.4.0") 2>&5
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"Qt5Widgets Qt5Gui Qt5Core >= 5.0.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "Qt5Widgets Qt5Gui Qt5Core >= 5.0.0") 2>&5
   ac_status=$?
   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
   test $ac_status = 0; }; then
-  pkg_cv_QT4_CFLAGS=`$PKG_CONFIG --cflags "QtCore QtGui >= 4.4.0" 2>/dev/null`
+  pkg_cv_QT5_CFLAGS=`$PKG_CONFIG --cflags "Qt5Widgets Qt5Gui Qt5Core >= 5.0.0" 2>/dev/null`
 		      test "x$?" != "x0" && pkg_failed=yes
 else
   pkg_failed=yes
@@ -17091,16 +17091,16 @@ fi
  else
     pkg_failed=untried
 fi
-if test -n "$QT4_LIBS"; then
-    pkg_cv_QT4_LIBS="$QT4_LIBS"
+if test -n "$QT5_LIBS"; then
+    pkg_cv_QT5_LIBS="$QT5_LIBS"
  elif test -n "$PKG_CONFIG"; then
     if test -n "$PKG_CONFIG" && \
-    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"QtCore QtGui >= 4.4.0\""; } >&5
-  ($PKG_CONFIG --exists --print-errors "QtCore QtGui >= 4.4.0") 2>&5
+    { { $as_echo "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"Qt5Widgets Qt5Gui Qt5Core >= 5.0.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "Qt5Widgets Qt5Gui Qt5Core >= 5.0.0") 2>&5
   ac_status=$?
   $as_echo "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
   test $ac_status = 0; }; then
-  pkg_cv_QT4_LIBS=`$PKG_CONFIG --libs "QtCore QtGui >= 4.4.0" 2>/dev/null`
+  pkg_cv_QT5_LIBS=`$PKG_CONFIG --libs "Qt5Widgets Qt5Gui Qt5Core >= 5.0.0" 2>/dev/null`
 		      test "x$?" != "x0" && pkg_failed=yes
 else
   pkg_failed=yes
@@ -17121,17 +17121,17 @@ else
         _pkg_short_errors_supported=no
 fi
         if test $_pkg_short_errors_supported = yes; then
-	        QT4_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "QtCore QtGui >= 4.4.0" 2>&1`
+	        QT5_PKG_ERRORS=`$PKG_CONFIG --short-errors --print-errors --cflags --libs "Qt5Widgets Qt5Gui Qt5Core >= 5.0.0" 2>&1`
         else
-	        QT4_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "QtCore QtGui >= 4.4.0" 2>&1`
+	        QT5_PKG_ERRORS=`$PKG_CONFIG --print-errors --cflags --libs "Qt5Widgets Qt5Gui Qt5Core >= 5.0.0" 2>&1`
         fi
 	# Put the nasty error message in config.log where it belongs
-	echo "$QT4_PKG_ERRORS" >&5
+	echo "$QT5_PKG_ERRORS" >&5
 
 
 
-			   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Cannot find Qt4 files - unable to build xcwcp" >&5
-$as_echo "$as_me: WARNING: Cannot find Qt4 files - unable to build xcwcp" >&2;}
+			   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Cannot find Qt5 files - unable to build xcwcp" >&5
+$as_echo "$as_me: WARNING: Cannot find Qt5 files - unable to build xcwcp" >&2;}
 
 			   WITH_XCWCP='no'
 
@@ -17141,19 +17141,19 @@ elif test $pkg_failed = untried; then
 $as_echo "no" >&6; }
 
 
-			   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Cannot find Qt4 files - unable to build xcwcp" >&5
-$as_echo "$as_me: WARNING: Cannot find Qt4 files - unable to build xcwcp" >&2;}
+			   { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Cannot find Qt5 files - unable to build xcwcp" >&5
+$as_echo "$as_me: WARNING: Cannot find Qt5 files - unable to build xcwcp" >&2;}
 
 			   WITH_XCWCP='no'
 
 
 else
-	QT4_CFLAGS=$pkg_cv_QT4_CFLAGS
-	QT4_LIBS=$pkg_cv_QT4_LIBS
+	QT5_CFLAGS=$pkg_cv_QT5_CFLAGS
+	QT5_LIBS=$pkg_cv_QT5_LIBS
         { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 $as_echo "yes" >&6; }
 
-			   for ac_prog in moc-qt4 moc
+			   for ac_prog in moc-qt5 moc
 do
   # Extract the first word of "$ac_prog", so it can be a program name with args.
 set dummy $ac_prog; ac_word=$2
@@ -17168,7 +17168,7 @@ else
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in `eval $PKG_CONFIG --variable=exec_prefix QtCore`/bin
+for as_dir in `eval $PKG_CONFIG --variable=host_bins Qt5Core`
 do
   IFS=$as_save_IFS
   test -z "$as_dir" && as_dir=.
@@ -17200,10 +17200,10 @@ done
 test -n "$MOC" || MOC="moc"
 
 
-			   { $as_echo "$as_me:${as_lineno-$LINENO}: result: QT4 CLFAGS is $QT4_CFLAGS" >&5
-$as_echo "QT4 CLFAGS is $QT4_CFLAGS" >&6; }
-			   { $as_echo "$as_me:${as_lineno-$LINENO}: result: QT4 LIBS is $QT4_LIBS" >&5
-$as_echo "QT4 LIBS is $QT4_LIBS" >&6; }
+			   { $as_echo "$as_me:${as_lineno-$LINENO}: result: QT5 CLFAGS is $QT5_CFLAGS" >&5
+$as_echo "QT5 CLFAGS is $QT5_CFLAGS" >&6; }
+			   { $as_echo "$as_me:${as_lineno-$LINENO}: result: QT5 LIBS is $QT5_LIBS" >&5
+$as_echo "QT5 LIBS is $QT5_LIBS" >&6; }
 
 
 
@@ -20922,12 +20922,12 @@ if test "$enable_experimental_receiver" = 'yes' ; then
 $as_echo "$as_me: enable experimental receiver code: ......  $enable_experimental_receiver" >&6;}
 fi
 if test "$WITH_XCWCP" = 'yes' ; then
-    { $as_echo "$as_me:${as_lineno-$LINENO}:     Qt4 CFLAGS:  $QT4_CFLAGS" >&5
-$as_echo "$as_me:     Qt4 CFLAGS:  $QT4_CFLAGS" >&6;}
-    { $as_echo "$as_me:${as_lineno-$LINENO}:     Qt4 LIBS:    $QT4_LIBS" >&5
-$as_echo "$as_me:     Qt4 LIBS:    $QT4_LIBS" >&6;}
-    { $as_echo "$as_me:${as_lineno-$LINENO}:     Qt4 MOC:     $MOC" >&5
-$as_echo "$as_me:     Qt4 MOC:     $MOC" >&6;}
+    { $as_echo "$as_me:${as_lineno-$LINENO}:     Qt5 CFLAGS:  $QT5_CFLAGS" >&5
+$as_echo "$as_me:     Qt5 CFLAGS:  $QT5_CFLAGS" >&6;}
+    { $as_echo "$as_me:${as_lineno-$LINENO}:     Qt5 LIBS:    $QT5_LIBS" >&5
+$as_echo "$as_me:     Qt5 LIBS:    $QT5_LIBS" >&6;}
+    { $as_echo "$as_me:${as_lineno-$LINENO}:     Qt5 MOC:     $MOC" >&5
+$as_echo "$as_me:     Qt5 MOC:     $MOC" >&6;}
 fi
 if test "$WITH_DEV" = 'yes' ; then
    { $as_echo "$as_me:${as_lineno-$LINENO}: enable dev support: .....................  yes" >&5
